version: '3.8'
services:
  gorangen-bot:
    build: ./deploy
    container_name: gorangen-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHATID=${TG_CHATID}
      - MON_INTERVAL=15
      - TRAILING_ATR_MULT=1.5
    volumes:
      - ./bot:/app/bot
      - ./pine:/app/pine
      - ./webhook:/app/webhook
      - ./tools:/app/tools
