"""The invoice and the delivery order, generated by the system.

Asked for, on a screenshot of the issue card: *"Invoice dan DO generate di
sistem seperti PO dan PR"* — produce them the way the purchase order and the
price request are already produced — and generate the file *after* approval.
Two of the company's own sheets came attached as the specification: the
delivery order that comes back stamped RECEIVED, and the invoice with the BCA
account printed under the lines.

Until now both were uploads. Somebody typed the invoice in Excel, saved a
PDF, and attached it to a record that already held the same figures — so the
document a customer received and the record the company reported on were two
different things maintained by hand, and a correction to one silently left
the other stale. The delivery order had it worse: the record carried no lines
at all, so there was nothing to print even in principle.

What this pins down:

**Nothing prints before somebody signs off.** The invoice's sheet exists
once finance has approved it with a faktur pajak number; the delivery
order's once the director has released it. Asking earlier is refused with
the reason, not with an empty PDF.

**A released document is frozen.** The row a sheet was printed from has to
keep saying what the paper says, so approving a DO closes the edit and
delete that were open before it — which is the same rule as "sebelum di
approve bisa edit dan hapus", now that approval is a real step. Withdrawing
the approval reopens it, and is itself refused once the goods are signed for.

**The delivery order knows what is on the truck.** Lines are copied from the
customer's own PO when it is issued, and carry no prices: it is signed at a
gate by whoever is standing there.

**The invoice sheet adds up.** Its lines are the customer's order, printed
only while they still explain the amount being billed; once the amount has
been corrected away from them, the sheet states the job as one line at the
invoiced figure rather than showing detail that contradicts its own total.
"""
import asyncio, os, sys, uuid
os.environ.update(DATABASE_URL="postgresql+asyncpg://postgres@127.0.0.1:55432/transmisi_test",
    APP_ENV="dev", DEMO_SEED_PASSWORD="test-pass-123",
    STORAGE_LOCAL_DIR="/tmp/storage_test", JWT_SECRET="e2e-test-secret")
sys.path.insert(0, "/home/user/Gay-boy-/backend")
import httpx, logging; logging.disable(logging.INFO)
PASS, FAIL = [], []
def check(n, c, d=""):
    (PASS if c else FAIL).append(n); print(("  PASS " if c else "  FAIL ")+n+(f"  [{d}]" if d and not c else ""))
def J(r):
    try: return r.json()
    except Exception: return {"_": r.text[:200]}


def pdf_text(blob: bytes) -> str:
    """What the sheet actually says, so the checks read the paper."""
    import fitz
    with fitz.open(stream=blob, filetype="pdf") as doc:
        return " ".join(p.get_text() for p in doc)


async def main():
    from app.scripts.seed import ensure_schema; await ensure_schema()
    from app.main import app
    c = httpx.AsyncClient(transport=httpx.ASGITransport(app=app),
                          base_url="http://t/api/v1", timeout=180)
    tag = uuid.uuid4().hex[:5]

    async def login(e):
        r = await c.post("/auth/login", json={"email": e, "password": "test-pass-123"})
        return {"Authorization": f"Bearer {r.json()['access_token']}"}
    d = await login("director@demo.local")
    adm = await login("admin@demo.local")
    fin = await login("finance@demo.local")
    s1 = await login("sales1@demo.local")
    mgr = await login("manager@demo.local")
    pur = await login("purchasing@demo.local")

    cust = J(await c.post("/customers", headers=s1, json={
        "company_name": f"PT Tanjung {tag}", "industry": "mining",
        "company_address": "Menara Karya Lt.7E\nJl. HR Rasuna Said, Jakarta Selatan",
        "delivery_address": "SITE OFFICE, JL. A. YANI RT 1/RW 1\nKAB. TABALONG, KALIMANTAN SELATAN",
        "phone": "021-25533095"}))["id"]
    pr = J(await c.post("/price-requests", headers=s1, json={
        "customer_id": cust,
        "items": [{"description": f"CHAIN SPROCKET TYPE B {tag}", "qty": 2,
                   "uom": "EA"}]}))["id"]
    await c.post(f"/price-requests/{pr}/submit", headers=s1)
    await c.post(f"/price-requests/{pr}/price", headers=d, json={
        "items": [{"line_no": 1, "cost_price": 1_000_000, "basis": "unit"}]})
    await c.post(f"/price-requests/{pr}/approve", headers=d, json={
        "items": [{"line_no": 1, "sell_price": 2_000_000, "basis": "unit"}]})
    q = J(await c.post(f"/quotations/from-price-request/{pr}", headers=s1))["id"]
    await c.post(f"/quotations/{q}/submit", headers=s1)
    await c.post(f"/quotations/{q}/approve", headers=d, json={"notes": ""})
    po_no = f"6300-PC{tag}"
    cpo = J(await c.post("/customer-pos", headers=s1, json={
        "customer_id": cust, "quotation_id": q, "number": po_no,
        "items": [{"description": f"CHAIN SPROCKET TYPE B {tag}", "qty": 2,
                   "uom": "EA", "unit_price": 2_000_000}],
        "is_downpayment": False}))["id"]
    await c.post(f"/quotations/{q}/won", headers=d)
    proj = J(await c.post(f"/customer-pos/{cpo}/approve", headers=d,
                          json={"notes": ""}))["project_id"]
    await c.post(f"/operation/projects/{proj}/qc", headers=adm,
                 json={"decision": "pass"})

    async def full():
        return J(await c.get(f"/operation/projects/{proj}/full", headers=d))

    # ══ admin issues the pair ════════════════════════════════════════════════
    print("\n── admin issues the invoice and the delivery order ──")
    r = await c.post(f"/operation/projects/{proj}/issue-invoice", headers=adm,
                     data={"invoice_type": "final"})
    check("admin can issue them", r.status_code == 201, f"{r.status_code} {J(r)}"[:170])
    issued = J(r)
    inv_id = issued["invoice"]["id"]
    do_id = issued["delivery_order"]["id"]
    check("...and both come out of the one action",
          bool(inv_id) and bool(do_id), str(issued)[:200])

    row = next(x for x in (await full())["deliveries"] if x["id"] == do_id)
    check("the delivery order knows what is on the truck",
          len(row["items"]) == 1
          and str(row["items"][0]["description"]).startswith("CHAIN SPROCKET"),
          str(row["items"])[:200])
    check("...in the customer's own words and quantity",
          float(row["items"][0]["qty"]) == 2.0 and row["items"][0]["uom"] == "EA",
          str(row["items"][0]))
    check("...and carries no prices — it is signed at a gate",
          all("price" not in k for i in row["items"] for k in i),
          str(row["items"][0]))
    check("...with the site address for the Remarks column",
          "TABALONG" in (row["remarks"] or ""), str(row["remarks"]))

    # ══ nothing prints before sign-off ═══════════════════════════════════════
    print("\n── before anybody has signed off ──")
    r = await c.get(f"/operation/deliveries/{do_id}/pdf", headers=adm)
    check("the delivery order's sheet is refused", r.status_code == 409,
          f"{r.status_code} {J(r)}"[:150])
    check("...saying the director releases it",
          "approv" in str(J(r)).lower(), str(J(r))[:170])
    r = await c.get(f"/finance/invoices/{inv_id}/pdf", headers=adm)
    check("the invoice's sheet is refused too", r.status_code == 409,
          f"{r.status_code} {J(r)}"[:150])
    check("...saying finance signs it with the faktur pajak number",
          "faktur pajak" in str(J(r)).lower(), str(J(r))[:170])

    # ══ the director releases the delivery order ═════════════════════════════
    print("\n── the director releases the delivery order ──")
    r = await c.post(f"/operation/deliveries/{do_id}/approve", headers=adm)
    check("admin cannot release it themselves", r.status_code == 403,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.post(f"/operation/deliveries/{do_id}/approve", headers=s1)
    check("...nor sales", r.status_code in (401, 403), str(r.status_code))
    r = await c.post(f"/operation/deliveries/{do_id}/approve", headers=d)
    check("the director can", r.status_code == 200, f"{r.status_code} {J(r)}"[:150])
    row = next(x for x in (await full())["deliveries"] if x["id"] == do_id)
    check("...and the project page says who and when",
          row["approved_at"] and row["approved_by_name"], str(row)[:200])

    r = await c.get(f"/operation/deliveries/{do_id}/pdf", headers=adm)
    check("now the sheet is generated", r.status_code == 200
          and r.content[:4] == b"%PDF", f"{r.status_code} {r.content[:20]}")
    sheet = pdf_text(r.content)
    check("...headed as a delivery order", "SURAT JALAN" in sheet.upper(),
          sheet[:200])
    check("...naming the customer", f"PT TANJUNG {tag}".upper() in sheet.upper(),
          sheet[:400])
    check("...their own PO as the reference", po_no in sheet, sheet[:500])
    check("...the goods and the count",
          "CHAIN SPROCKET" in sheet.upper() and "2" in sheet, sheet[:600])
    check("...where the goods are going", "TABALONG" in sheet.upper(), sheet[:800])
    check("...the three signature boxes, two of them blank for a pen",
          "Prepared by" in sheet and "Sent by" in sheet and "Received by" in sheet,
          sheet[-400:])
    check("...and no price anywhere on it",
          "2.000.000" not in sheet and "4.000.000" not in sheet, sheet[:900])

    # ══ a released document is frozen ════════════════════════════════════════
    print("\n── once released ──")
    r = await c.patch(f"/operation/deliveries/{do_id}", headers=adm,
                      json={"courier": "Someone else"})
    check("editing it is refused", r.status_code == 409,
          f"{r.status_code} {J(r)}"[:150])
    check("...because the printed copy has to keep saying what this says",
          "printed" in str(J(r)).lower(), str(J(r))[:200])
    r = await c.delete(f"/operation/deliveries/{do_id}", headers=adm)
    check("deleting it is refused", r.status_code == 409,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.post(f"/operation/deliveries/{do_id}/unapprove", headers=adm)
    check("admin cannot withdraw the approval", r.status_code == 403,
          str(r.status_code))
    r = await c.post(f"/operation/deliveries/{do_id}/unapprove", headers=d)
    check("the director can withdraw it", r.status_code == 200,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.patch(f"/operation/deliveries/{do_id}", headers=adm,
                      json={"courier": "JNE Trucking"})
    check("...which reopens the edit", r.status_code == 200,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.get(f"/operation/deliveries/{do_id}/pdf", headers=adm)
    check("...and stops the sheet printing again", r.status_code == 409,
          str(r.status_code))
    await c.post(f"/operation/deliveries/{do_id}/approve", headers=d)
    sheet = pdf_text((await c.get(f"/operation/deliveries/{do_id}/pdf",
                                  headers=adm)).content)
    check("re-approving reissues it with the correction on it",
          "JNE Trucking" in sheet, sheet[:600])

    # ══ the invoice ══════════════════════════════════════════════════════════
    print("\n── finance signs the invoice ──")
    fp = f"010.000-26.{tag}"
    r = await c.post(f"/finance/invoices/{inv_id}/approve", headers=fin,
                     data={"faktur_pajak_no": fp})
    check("finance approves it with its faktur pajak number", r.status_code < 300,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.get(f"/finance/invoices/{inv_id}/pdf", headers=adm)
    check("now the invoice sheet is generated",
          r.status_code == 200 and r.content[:4] == b"%PDF",
          f"{r.status_code} {r.content[:20]}")
    sheet = pdf_text(r.content)
    check("...addressed to the customer",
          f"PT TANJUNG {tag}".upper() in sheet.upper(), sheet[:400])
    check("...with the customer's order number on it", po_no in sheet, sheet[:600])
    check("...the faktur pajak number", fp in sheet, sheet[:600])
    check("...the order's own line", "CHAIN SPROCKET" in sheet.upper(), sheet[:700])
    check("...the money in three parts", "SUB BRUTO" in sheet.upper()
          and "PPN" in sheet.upper() and "SUB TOTAL" in sheet.upper(), sheet[:900])
    check("...and where to pay", "578-5523889" in sheet and "BCA" in sheet.upper(),
          sheet[-500:])

    # A corrected amount the order lines no longer explain.
    print("\n── an invoice whose figure was corrected ──")
    r = await c.post(f"/operation/projects/{proj}/issue-invoice", headers=adm,
                     data={"invoice_type": "final"})
    inv2 = J(r)["invoice"]["id"]
    await c.patch(f"/finance/invoices/{inv2}", headers=adm,
                  json={"amount": 1_234_567, "tax_amount": 0})
    await c.post(f"/finance/invoices/{inv2}/approve", headers=fin,
                 data={"faktur_pajak_no": f"010.000-26.B{tag}"})
    sheet = pdf_text((await c.get(f"/finance/invoices/{inv2}/pdf",
                                  headers=fin)).content)
    check("the sheet states the job as one line at the invoiced figure",
          "1.234.567" in sheet, sheet[:800])
    check("...rather than order lines that contradict the total",
          "CHAIN SPROCKET" not in sheet.upper(), sheet[:800])

    # ══ who may fetch a sheet ════════════════════════════════════════════════
    print("\n── who may print them ──")
    for who, hdr, ok_do in (("the manager", mgr, True), ("purchasing", pur, False),
                            ("sales", s1, False)):
        r = await c.get(f"/operation/deliveries/{do_id}/pdf", headers=hdr)
        got = r.status_code == 200
        check(f"{who} {'can' if ok_do else 'cannot'} print the delivery order",
              got == ok_do, str(r.status_code))
    for who, hdr, ok_inv in (("finance", fin, True), ("the director", d, True),
                             ("sales", s1, False), ("purchasing", pur, False)):
        r = await c.get(f"/finance/invoices/{inv_id}/pdf", headers=hdr)
        got = r.status_code == 200
        check(f"{who} {'can' if ok_inv else 'cannot'} print the invoice",
              got == ok_inv, str(r.status_code))

    # ══ a delivery order with nothing on it ══════════════════════════════════
    print("\n── a delivery order with no lines ──")
    empty = J(await c.post(f"/operation/projects/{proj}/delivery", headers=adm,
                           json={"number": f"DO-MANUAL-{tag}", "split_index": 2}))["id"]
    r = await c.post(f"/operation/deliveries/{empty}/approve", headers=d)
    check("it can't be released — there is nothing to sign for",
          r.status_code == 409, f"{r.status_code} {J(r)}"[:150])
    r = await c.patch(f"/operation/deliveries/{empty}", headers=adm, json={
        "items": [{"description": f"SPARE LINK {tag}", "qty": 4, "uom": "PCS"}],
        "remarks": "BARANG DI KIRIM KE: GUDANG SITE"})
    check("...so admin types what is going", r.status_code == 200,
          f"{r.status_code} {J(r)}"[:150])
    r = await c.post(f"/operation/deliveries/{empty}/approve", headers=mgr)
    check("...and the manager can then release it", r.status_code == 200,
          f"{r.status_code} {J(r)}"[:150])
    sheet = pdf_text((await c.get(f"/operation/deliveries/{empty}/pdf",
                                  headers=adm)).content)
    check("...with the typed lines on the sheet",
          "SPARE LINK" in sheet.upper() and "GUDANG SITE" in sheet.upper(),
          sheet[:700])

    await c.aclose()
    print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
    if FAIL:
        print("FAILED: " + "; ".join(FAIL)); sys.exit(1)


asyncio.run(main())
