import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Trash2, Loader2, AlertTriangle, ShieldAlert, Check, Users, Eye, CheckCircle2,
  ListChecks,
} from "lucide-react";
import clsx from "clsx";
import { api } from "@/api/client";
import { useT } from "@/store/lang";
import RecordDelete from "@/components/RecordDelete";

interface Owner {
  id: string; full_name: string; email: string; role: string; is_active: boolean;
  customers: number; price_requests: number; quotations: number;
  customer_pos: number; projects: number;
}
interface CustomerRow { id: string; name: string; stage: string | null; why: string[] }
interface Preview {
  confirm_phrase: string;
  keeping: { id: string; full_name: string; role: string }[];
  counts: Record<string, number>;
  customers_to_delete: CustomerRow[];
  customers_to_keep: CustomerRow[];
  kept_customer_count: number;
}

/** The order the numbers read best in — roughly the order of the pipeline. */
const COUNT_ORDER = [
  "customers", "contacts", "price_requests", "quotations", "quotation_items",
  "customer_pos", "projects", "work_orders", "drawings", "delivery_orders",
  "invoices", "payments", "ledger_entries", "supplier_pos", "purchase_requests",
  "rfqs", "attachments", "discussion_messages", "approval_requests",
];

const LABEL: Record<string, [string, string]> = {
  customers: ["Customers", "Pelanggan"],
  contacts: ["Contacts", "Kontak"],
  price_requests: ["Price requests", "Permintaan harga"],
  quotations: ["Quotations", "Penawaran"],
  quotation_items: ["Quotation lines", "Baris penawaran"],
  customer_pos: ["Customer POs", "PO pelanggan"],
  projects: ["Projects", "Proyek"],
  work_orders: ["Work orders", "Perintah kerja"],
  drawings: ["Drawings", "Gambar"],
  delivery_orders: ["Delivery orders", "Surat jalan"],
  invoices: ["Invoices", "Faktur"],
  payments: ["Payments", "Pembayaran"],
  ledger_entries: ["Ledger entries", "Jurnal"],
  supplier_pos: ["Supplier POs", "PO supplier"],
  purchase_requests: ["Purchase requests", "Permintaan pembelian"],
  rfqs: ["RFQs", "RFQ"],
  attachments: ["Files", "Berkas"],
  discussion_messages: ["Discussion messages", "Pesan diskusi"],
  approval_requests: ["Approval requests", "Permintaan persetujuan"],
};

/**
 * Clear the test data left over from building the system.
 *
 * Deliberately a three-step screen — choose, preview, confirm — because the
 * delete cannot be undone from inside the app. Nothing happens until the
 * confirmation phrase is typed, and the preview above it is generated by the
 * same code that does the deleting, so the numbers cannot drift apart.
 */
export default function DataCleanupPage() {
  const t = useT();
  // Two tools, and which one is right depends entirely on how much is left.
  // The sweep is for the first pass — thousands of rows from months of
  // development. Picking records is for everything after that, and for the
  // test row that belongs to a real person, which the sweep protects.
  const [mode, setMode] = useState<"owner" | "records">("owner");
  const [keep, setKeep] = useState<Set<string>>(new Set());
  const [preview, setPreview] = useState<Preview | null>(null);
  const [phrase, setPhrase] = useState("");
  const [done, setDone] = useState<Record<string, number> | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const owners = useQuery({
    queryKey: ["data-owners"],
    queryFn: () => api.get("/maintenance/data-owners").then((r) => r.data as Owner[]),
  });

  const fail = (e: any) => setErr(
    e?.response?.data?.errors?.[0]?.message
    ?? e?.response?.data?.detail
    ?? t("Something went wrong", "Terjadi kesalahan"),
  );

  const runPreview = useMutation({
    mutationFn: () => api.post("/maintenance/purge/preview", {
      keep_user_ids: Array.from(keep),
    }).then((r) => r.data as Preview),
    onSuccess: (d) => { setPreview(d); setErr(null); setPhrase(""); },
    onError: fail,
  });

  const runPurge = useMutation({
    mutationFn: () => api.post("/maintenance/purge/execute", {
      keep_user_ids: Array.from(keep), confirm: phrase,
    }).then((r) => r.data as { deleted: Record<string, number> }),
    onSuccess: (d) => { setDone(d.deleted); setPreview(null); setPhrase(""); setErr(null); },
    onError: fail,
  });

  const rows = owners.data ?? [];
  const total = (o: Owner) =>
    o.customers + o.price_requests + o.quotations + o.customer_pos + o.projects;
  const armed = !!preview && phrase === preview.confirm_phrase;
  const willDelete = preview
    ? COUNT_ORDER.reduce((n, k) => n + (preview.counts[k] ?? 0), 0) : 0;

  function toggle(id: string) {
    const next = new Set(keep);
    next.has(id) ? next.delete(id) : next.add(id);
    setKeep(next);
    setPreview(null);          // the plan is stale the moment the choice changes
    setDone(null);
  }

  return (
    <div className="space-y-5 max-w-5xl">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2">
          <Trash2 size={22} className="text-accent-500" />
          {t("Clear test data", "Hapus data uji coba")}
        </h1>
        <p className="text-sm muted mt-1">
          {mode === "owner"
            ? t("Deletes the customers, price requests, quotations, POs and projects that belong to nobody you keep — along with everything filed under them.",
                "Menghapus pelanggan, permintaan harga, penawaran, PO dan proyek yang bukan milik orang yang Anda pertahankan — beserta semua isinya.")
            : t("Deletes exactly the documents you pick, and everything created from them.",
                "Menghapus dokumen yang Anda pilih saja, beserta semua yang dibuat darinya.")}
        </p>
      </div>

      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setMode("owner")}
          className={clsx("flex items-center gap-2 rounded-lg border px-3 py-2 text-sm",
            mode === "owner"
              ? "border-brand-600 bg-brand-50 text-brand-700 font-semibold dark:bg-brand-500/15"
              : "border-ink-200 hover:bg-ink-50")}
        >
          <Users size={15} />
          {t("Sweep by owner", "Sapu per pemilik")}
        </button>
        <button
          onClick={() => setMode("records")}
          className={clsx("flex items-center gap-2 rounded-lg border px-3 py-2 text-sm",
            mode === "records"
              ? "border-brand-600 bg-brand-50 text-brand-700 font-semibold dark:bg-brand-500/15"
              : "border-ink-200 hover:bg-ink-50")}
        >
          <ListChecks size={15} />
          {t("Pick specific records", "Pilih data tertentu")}
        </button>
      </div>

      <div className="card p-4 border-l-2 border-l-accent-500">
        <div className="flex items-start gap-2 text-sm">
          <ShieldAlert size={16} className="text-accent-500 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <div className="font-semibold">
              {t("This cannot be undone from inside the app.",
                 "Ini tidak bisa dibatalkan dari dalam aplikasi.")}
            </div>
            <p className="muted">
              {t("Take a database backup first — in Neon, create a branch of the current state. A customer cannot be deleted without its whole history, so its invoices, payments and ledger entries go with it.",
                 "Buat cadangan basis data dulu — di Neon, buat branch dari kondisi saat ini. Pelanggan tidak bisa dihapus tanpa seluruh riwayatnya, jadi faktur, pembayaran, dan jurnalnya ikut terhapus.")}
            </p>
          </div>
        </div>
      </div>

      {mode === "records" && <RecordDelete />}

      {mode === "owner" && err && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-800">
          {err}
        </div>
      )}

      {mode === "owner" && done && (
        <div className="card p-4 border-l-2 border-l-emerald-500">
          <div className="flex items-center gap-2 font-semibold text-emerald-700">
            <CheckCircle2 size={16} /> {t("Done", "Selesai")}
          </div>
          <div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm">
            {COUNT_ORDER.filter((k) => done[k]).map((k) => (
              <span key={k}>
                <b>{done[k]}</b>{" "}
                <span className="muted">{t(LABEL[k][0], LABEL[k][1]).toLowerCase()}</span>
              </span>
            ))}
            {!COUNT_ORDER.some((k) => done[k]) && (
              <span className="muted">{t("Nothing needed deleting.", "Tidak ada yang perlu dihapus.")}</span>
            )}
          </div>
        </div>
      )}

      {/* ── Step 1 ─────────────────────────────────────────────────────────── */}
      {mode === "owner" && (
      <div className="card overflow-hidden">
        <header className="px-4 py-3 border-b border-ink-100 flex items-center gap-2">
          <Users size={15} className="text-brand-600" />
          <span className="font-semibold">
            {t("1. Whose data is real?", "1. Data siapa yang asli?")}
          </span>
          <span className="ml-auto text-xs muted">
            {t(`${keep.size} selected`, `${keep.size} dipilih`)}
          </span>
        </header>
        <p className="px-4 pt-3 text-sm muted">
          {t("Tick the people who entered genuine records. Everyone else's customers are treated as test data.",
             "Centang orang yang memasukkan data asli. Pelanggan milik orang lain dianggap data uji coba.")}
        </p>
        <div className="p-3 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left">
                <th className="w-8" />
                <th>{t("Name", "Nama")}</th>
                <th>{t("Role", "Peran")}</th>
                <th className="text-right">{t("Customers", "Pelanggan")}</th>
                <th className="text-right">{t("Price req.", "Permintaan")}</th>
                <th className="text-right">{t("Quotes", "Penawaran")}</th>
                <th className="text-right">{t("POs", "PO")}</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((o) => (
                <tr
                  key={o.id}
                  onClick={() => toggle(o.id)}
                  className={clsx("cursor-pointer border-t border-ink-100",
                    keep.has(o.id) ? "bg-brand-50/60" : "hover:bg-ink-50",
                    total(o) === 0 && "opacity-60")}
                >
                  <td className="py-2">
                    <span className={clsx(
                      "inline-grid place-items-center h-4 w-4 rounded border",
                      keep.has(o.id)
                        ? "bg-brand-600 border-brand-600 text-white"
                        : "border-ink-300")}>
                      {keep.has(o.id) && <Check size={11} />}
                    </span>
                  </td>
                  <td className="py-2">
                    <div className="font-medium">{o.full_name}</div>
                    <div className="text-[11px] muted">{o.email}</div>
                  </td>
                  <td className="py-2 text-[11px] uppercase tracking-wide muted">{o.role}</td>
                  <td className="py-2 text-right spec">{o.customers}</td>
                  <td className="py-2 text-right spec">{o.price_requests}</td>
                  <td className="py-2 text-right spec">{o.quotations}</td>
                  <td className="py-2 text-right spec">{o.customer_pos}</td>
                </tr>
              ))}
              {owners.isLoading && (
                <tr><td colSpan={7} className="py-6 text-center muted">
                  <Loader2 size={14} className="animate-spin inline" /> {t("Loading…", "Memuat…")}
                </td></tr>
              )}
            </tbody>
          </table>
        </div>
        <footer className="px-4 py-3 border-t border-ink-100">
          <button
            className="btn-primary"
            disabled={!keep.size || runPreview.isPending}
            onClick={() => runPreview.mutate()}
          >
            {runPreview.isPending
              ? <Loader2 size={14} className="animate-spin" />
              : <Eye size={14} />}
            {t("Preview what would be deleted", "Lihat yang akan dihapus")}
          </button>
        </footer>
      </div>
      )}

      {/* ── Step 2 ─────────────────────────────────────────────────────────── */}
      {mode === "owner" && preview && (
        <>
          <div className="card overflow-hidden">
            <header className="px-4 py-3 border-b border-ink-100 font-semibold">
              {t("2. What this would delete", "2. Yang akan dihapus")}
            </header>
            <div className="p-4 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              {COUNT_ORDER.map((k) => (
                <div key={k} className={clsx("rounded-lg border px-3 py-2",
                  preview.counts[k] ? "border-red-200 bg-red-50" : "border-ink-200")}>
                  <div className="text-xl font-semibold spec">{preview.counts[k] ?? 0}</div>
                  <div className="text-[11px] muted">{t(LABEL[k][0], LABEL[k][1])}</div>
                </div>
              ))}
            </div>
            <div className="px-4 pb-4 grid gap-4 lg:grid-cols-2">
              <div>
                <div className="overline mb-1 text-red-700">
                  {t(`Deleting ${preview.customers_to_delete.length} customers`,
                     `Menghapus ${preview.customers_to_delete.length} pelanggan`)}
                </div>
                <div className="max-h-56 overflow-y-auto rounded-lg border border-ink-200 divide-y divide-ink-100">
                  {preview.customers_to_delete.map((cst) => (
                    <div key={cst.id} className="px-3 py-1.5 text-sm">{cst.name}</div>
                  ))}
                  {!preview.customers_to_delete.length && (
                    <div className="px-3 py-2 text-sm muted">{t("None", "Tidak ada")}</div>
                  )}
                </div>
              </div>
              <div>
                <div className="overline mb-1 text-emerald-700">
                  {t(`Keeping ${preview.kept_customer_count} customers`,
                     `Menyimpan ${preview.kept_customer_count} pelanggan`)}
                </div>
                <div className="max-h-56 overflow-y-auto rounded-lg border border-ink-200 divide-y divide-ink-100">
                  {preview.customers_to_keep.map((cst) => (
                    <div key={cst.id} className="px-3 py-1.5 text-sm">
                      {cst.name}
                      {cst.why?.length > 0 && (
                        <span className="muted text-[11px]"> · {cst.why.join(", ")}</span>
                      )}
                    </div>
                  ))}
                  {!preview.customers_to_keep.length && (
                    <div className="px-3 py-2 text-sm muted">{t("None", "Tidak ada")}</div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* ── Step 3 ───────────────────────────────────────────────────── */}
          <div className="card overflow-hidden border-l-2 border-l-red-500">
            <header className="px-4 py-3 border-b border-ink-100 font-semibold
                               flex items-center gap-2">
              <AlertTriangle size={15} className="text-red-600" />
              {t("3. Confirm", "3. Konfirmasi")}
            </header>
            <div className="p-4 space-y-3">
              <p className="text-sm">
                {t(`You are about to permanently delete ${willDelete} records across ${preview.customers_to_delete.length} customers. Type the phrase below to enable the button.`,
                   `Anda akan menghapus permanen ${willDelete} data dari ${preview.customers_to_delete.length} pelanggan. Ketik frasa di bawah untuk mengaktifkan tombolnya.`)}
              </p>
              <div className="flex flex-wrap items-center gap-2">
                <code className="rounded-lg bg-ink-100 px-2 py-1 text-sm font-mono">
                  {preview.confirm_phrase}
                </code>
                <input
                  className="input max-w-xs font-mono"
                  value={phrase}
                  onChange={(e) => setPhrase(e.target.value)}
                  placeholder={preview.confirm_phrase}
                  autoComplete="off"
                />
                <button
                  className={clsx(armed ? "btn-danger" : "btn-ghost border-ink-200")}
                  disabled={!armed || runPurge.isPending}
                  onClick={() => runPurge.mutate()}
                >
                  {runPurge.isPending
                    ? <Loader2 size={14} className="animate-spin" />
                    : <Trash2 size={14} />}
                  {t("Delete permanently", "Hapus permanen")}
                </button>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
